Projeto bot de cotação do dolar.
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
#
# Initial commit
#
# Changes to be committed:
#	new file:   .env.example
#	new file:   .gitattributes
#	new file:   .gitignore
#	new file:   app/BotCotacao/CotacaoUol.php
#	new file:   app/BotCotacao/TelegramBot.php
#	new file:   app/Console/Commands/Inspire.php
#	new file:   app/Console/Kernel.php
#	new file:   app/Events/Event.php
#	new file:   app/Exceptions/Handler.php
#	new file:   app/Http/Controllers/Auth/AuthController.php
#	new file:   app/Http/Controllers/Auth/PasswordController.php
#	new file:   app/Http/Controllers/Controller.php
#	new file:   app/Http/Controllers/CotacaoController.php
#	new file:   app/Http/Kernel.php
#	new file:   app/Http/Middleware/Authenticate.php
#	new file:   app/Http/Middleware/EncryptCookies.php
#	new file:   app/Http/Middleware/RedirectIfAuthenticated.php
#	new file:   app/Http/Middleware/VerifyCsrfToken.php
#	new file:   app/Http/Requests/Request.php
#	new file:   app/Http/routes.php
#	new file:   app/Jobs/Job.php
#	new file:   app/Listeners/.gitkeep
#	new file:   app/Policies/.gitkeep
#	new file:   app/Providers/AppServiceProvider.php
#	new file:   app/Providers/AuthServiceProvider.php
#	new file:   app/Providers/EventServiceProvider.php
#	new file:   app/Providers/RouteServiceProvider.php
#	new file:   app/User.php
#	new file:   artisan
#	new file:   bootstrap/app.php
#	new file:   bootstrap/autoload.php
#	new file:   bootstrap/cache/.gitignore
#	new file:   composer.json
#	new file:   composer.lock
#	new file:   config/app.php
#	new file:   config/auth.php
#	new file:   config/broadcasting.php
#	new file:   config/cache.php
#	new file:   config/compile.php
#	new file:   config/database.php
#	new file:   config/filesystems.php
#	new file:   config/mail.php
#	new file:   config/queue.php
#	new file:   config/services.php
#	new file:   config/session.php
#	new file:   config/view.php
#	new file:   database/.gitignore
#	new file:   database/factories/ModelFactory.php
#	new file:   database/migrations/.gitkeep
#	new file:   database/migrations/2014_10_12_000000_create_users_table.php
#	new file:   database/migrations/2014_10_12_100000_create_password_resets_table.php
#	new file:   database/seeds/.gitkeep
#	new file:   database/seeds/DatabaseSeeder.php
#	new file:   gulpfile.js
#	new file:   package.json
#	new file:   phpunit.xml
#	new file:   public/.htaccess
#	new file:   public/favicon.ico
#	new file:   public/index.php
#	new file:   public/robots.txt
#	new file:   public/web.config
#	new file:   readme.md
#	new file:   resources/assets/sass/app.scss
#	new file:   resources/lang/en/auth.php
#	new file:   resources/lang/en/pagination.php
#	new file:   resources/lang/en/passwords.php
#	new file:   resources/lang/en/validation.php
#	new file:   resources/views/cotacao.blade.php
#	new file:   resources/views/errors/503.blade.php
#	new file:   resources/views/vendor/.gitkeep
#	new file:   server.php
#	new file:   storage/app/.gitignore
#	new file:   storage/app/public/.gitignore
#	new file:   storage/framework/.gitignore
#	new file:   storage/framework/cache/.gitignore
#	new file:   storage/framework/sessions/.gitignore
#	new file:   storage/framework/views/.gitignore
#	new file:   storage/logs/.gitignore
#	new file:   tests/ExampleTest.php
#	new file:   tests/TestCase.php
#
